const dotenv = require('dotenv');

dotenv.config();

const products = [
  {
    name: "Radiance Vitamin C Serum",
    category: "Face Serums",
    price: 3735,
    mrp: 4980,
    discount: 25,
    images: ["/images/serum_yellow_bottle_1782982637214.png"],
    rating: 4.8,
    numReviews: 124,
    description: "A potent Vitamin C serum that brightens and evens skin tone while providing antioxidant protection.",
    ingredients: "Vitamin C, Hyaluronic Acid, Ferulic Acid",
    benefits: "Brightens skin, reduces dark spots, boosts collagen.",
    directions: "Apply 3-4 drops to clean, dry face morning and night.",
    skinType: "All skin types",
    weight: "30 ml",
    sku: "FG-SER-001"
  },
  {
    name: "Hydra-Bounce Moisturizer",
    category: "Moisturizers",
    price: 3154,
    mrp: 3735,
    discount: 15,
    images: ["/images/serum_splash_1782982723650.png"],
    rating: 4.9,
    numReviews: 89,
    description: "A lightweight, gel-cream moisturizer that delivers intense hydration without a heavy feel.",
    ingredients: "Hyaluronic Acid, Ceramide, Aloe Vera",
    benefits: "Deeply hydrates, plumps skin, restores barrier.",
    directions: "Massage onto face and neck after cleansing.",
    skinType: "Dry to Normal",
    weight: "50 ml",
    sku: "FG-MOI-002"
  },
  {
    name: "Gentle Purifying Face Wash",
    category: "Face Wash",
    price: 1826,
    mrp: 1826,
    discount: 0,
    images: ["/images/serum_flowers_1782982660822.png"],
    rating: 4.6,
    numReviews: 210,
    description: "A soothing, foaming cleanser that removes impurities without stripping the skin of natural oils.",
    ingredients: "Green Tea Extract, Niacinamide, Glycerin",
    benefits: "Cleanses pores, removes makeup, soothes skin.",
    directions: "Lather a coin-sized amount and massage onto damp face.",
    skinType: "Sensitive, Oily, Combination",
    weight: "150 ml",
    sku: "FG-WAS-003"
  },
  {
    name: "Sheer Defense SPF 50",
    category: "Sunscreens",
    price: 2656,
    mrp: 3320,
    discount: 20,
    images: ["/images/serum_candles_1782982698387.png"],
    rating: 4.7,
    numReviews: 156,
    description: "An invisible, weightless sunscreen that provides broad-spectrum UVA/UVB protection.",
    ingredients: "Zinc Oxide, Titanium Dioxide, Vitamin E",
    benefits: "Sun protection, anti-aging, non-greasy.",
    directions: "Apply generously 15 minutes before sun exposure.",
    skinType: "All skin types",
    weight: "50 ml",
    sku: "FG-SUN-004"
  },
  {
    name: "Glow Enhancing Lip Balm",
    category: "Lip Care",
    price: 1245,
    mrp: 1245,
    discount: 0,
    images: ["https://images.unsplash.com/photo-1586495777744-4413f21062fa?q=80&w=800&auto=format&fit=crop"],
    rating: 4.8,
    numReviews: 320,
    description: "A deeply nourishing lip balm that provides long-lasting moisture and a subtle tint.",
    ingredients: "Shea Butter, Jojoba Oil, Vitamin E",
    benefits: "Moisturizes, softens lips, subtle pink tint.",
    directions: "Apply to lips as needed throughout the day.",
    skinType: "All skin types",
    weight: "10 g",
    sku: "FG-LIP-005"
  },
  {
    name: "Revitalizing Night Cream",
    category: "Skincare",
    price: 4565,
    mrp: 5395,
    discount: 15,
    images: ["https://images.unsplash.com/photo-1601049541289-9b1b7ce817d2?q=80&w=800&auto=format&fit=crop"],
    rating: 4.9,
    numReviews: 95,
    description: "A rich night cream that repairs and rejuvenates your skin while you sleep.",
    ingredients: "Retinol, Peptides, Evening Primrose Oil",
    benefits: "Anti-aging, skin repair, firming.",
    directions: "Apply every evening to cleansed face and neck.",
    skinType: "Mature, Dry",
    weight: "50 ml",
    sku: "FG-SKI-006"
  },
  {
    name: "Silky Smooth Body Lotion",
    category: "Body Care",
    price: 2324,
    mrp: 2905,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?q=80&w=800&auto=format&fit=crop"],
    rating: 4.5,
    numReviews: 180,
    description: "A fast-absorbing body lotion that leaves your skin feeling soft, smooth, and deeply hydrated.",
    ingredients: "Cocoa Butter, Almond Oil, Vitamin E",
    benefits: "All-day moisture, softens skin, pleasant scent.",
    directions: "Massage onto body after showering.",
    skinType: "All skin types",
    weight: "250 ml",
    sku: "FG-BOD-007"
  },
  {
    name: "Flawless Finish Foundation",
    category: "Makeup",
    price: 3486,
    mrp: 3486,
    discount: 0,
    images: ["https://images.unsplash.com/photo-1596462502278-27bf84033005?q=80&w=800&auto=format&fit=crop"],
    rating: 4.4,
    numReviews: 310,
    description: "A buildable, medium-coverage foundation that gives a natural, flawless finish.",
    ingredients: "Squalane, Hyaluronic Acid, Mineral Pigments",
    benefits: "Even skin tone, long-lasting, hydrating.",
    directions: "Blend evenly over face using a brush or sponge.",
    skinType: "All skin types",
    weight: "30 ml",
    sku: "FG-MAK-008"
  },
  {
    name: "Nourishing Hair Mask",
    category: "Hair Care",
    price: 2905,
    mrp: 3735,
    discount: 22,
    images: ["https://images.unsplash.com/photo-1522337660859-02fbefca4702?q=80&w=800&auto=format&fit=crop"],
    rating: 4.7,
    numReviews: 145,
    description: "An intensive treatment mask that repairs damaged hair and restores shine.",
    ingredients: "Argan Oil, Keratin, Coconut Oil",
    benefits: "Repairs damage, adds shine, reduces frizz.",
    directions: "Apply to wet hair after shampooing. Leave on for 5-10 minutes, then rinse.",
    skinType: "N/A",
    weight: "200 ml",
    sku: "FG-HAI-009"
  },
  {
    name: "Ultimate Glow Gift Set",
    category: "Gift Sets",
    price: 7885,
    mrp: 9960,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1549465220-1a8b9238cd48?q=80&w=800&auto=format&fit=crop"],
    rating: 5.0,
    numReviews: 45,
    description: "The perfect gift featuring our top 3 best-selling skincare products.",
    ingredients: "Various",
    benefits: "Complete skincare routine in one box.",
    directions: "See individual products for directions.",
    skinType: "All skin types",
    weight: "Varies",
    sku: "FG-GIF-010"
  },
  {
    name: "Rose Quartz Facial Roller",
    category: "Skincare",
    price: 2075,
    mrp: 2490,
    discount: 16,
    images: ["https://images.unsplash.com/photo-1590156176508-c0b7fb5896a6?q=80&w=800&auto=format&fit=crop"],
    rating: 4.6,
    numReviews: 220,
    description: "A premium rose quartz roller to depuff, soothe, and massage the face.",
    ingredients: "100% Natural Rose Quartz",
    benefits: "Depuffs, stimulates circulation, helps product absorption.",
    directions: "Roll gently over face and neck in upward motions.",
    skinType: "All skin types",
    weight: "150 g",
    sku: "FG-SKI-011"
  },
  {
    name: "Clarifying Clay Mask",
    category: "Skincare",
    price: 2490,
    mrp: 2490,
    discount: 0,
    images: ["https://images.unsplash.com/photo-1570194065650-d99fb4b18b17?q=80&w=800&auto=format&fit=crop"],
    rating: 4.8,
    numReviews: 175,
    description: "A deeply purifying clay mask that draws out impurities and minimizes pores.",
    ingredients: "Kaolin Clay, Charcoal, Tea Tree Oil",
    benefits: "Unclogs pores, reduces excess oil, clears breakouts.",
    directions: "Apply a thin layer to clean skin. Leave on for 10-15 minutes, then rinse.",
    skinType: "Oily, Combination, Acne-prone",
    weight: "100 g",
    sku: "FG-SKI-012"
  },
  {
    name: "Volumizing Mascara",
    category: "Makeup",
    price: 1992,
    mrp: 1992,
    discount: 0,
    images: ["https://images.unsplash.com/photo-1512496015851-a9ed62aa2829?q=80&w=800&auto=format&fit=crop"],
    rating: 4.5,
    numReviews: 290,
    description: "A clump-free mascara that adds dramatic volume and length to your lashes.",
    ingredients: "Beeswax, Carnauba Wax, Panthenol",
    benefits: "Volumizes, lengthens, smudge-proof.",
    directions: "Wiggle brush from base of lashes to tip.",
    skinType: "N/A",
    weight: "8 ml",
    sku: "FG-MAK-013"
  },
  {
    name: "Luminous Highlighting Powder",
    category: "Makeup",
    price: 2656,
    mrp: 3154,
    discount: 15,
    images: ["https://images.unsplash.com/photo-1583241475880-083f84372725?q=80&w=800&auto=format&fit=crop"],
    rating: 4.7,
    numReviews: 110,
    description: "A finely milled highlighting powder for a natural, radiant glow.",
    ingredients: "Mica, Squalane, Pearl Powder",
    benefits: "Adds glow, blendable, long-wearing.",
    directions: "Dust over cheekbones, brow bone, and cupid's bow.",
    skinType: "All skin types",
    weight: "12 g",
    sku: "FG-MAK-014"
  },
  {
    name: "Nourishing Cuticle Oil",
    category: "Body Care",
    price: 1494,
    mrp: 1826,
    discount: 18,
    images: ["https://images.unsplash.com/photo-1522337660859-02fbefca4702?q=80&w=800&auto=format&fit=crop"],
    rating: 4.9,
    numReviews: 85,
    description: "A rich blend of natural oils to soften and condition cuticles and nails.",
    ingredients: "Jojoba Oil, Sweet Almond Oil, Vitamin E",
    benefits: "Softens cuticles, strengthens nails.",
    directions: "Brush onto cuticles and massage gently.",
    skinType: "N/A",
    weight: "15 ml",
    sku: "FG-BOD-015"
  },
  {
    name: "Revitalizing Eye Cream",
    category: "Skincare",
    price: 3984,
    mrp: 4980,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1615397323161-5509c25bbaf6?q=80&w=800&auto=format&fit=crop"],
    rating: 4.6,
    numReviews: 130,
    description: "A targeted eye cream that reduces the appearance of dark circles and fine lines.",
    ingredients: "Caffeine, Peptides, Hyaluronic Acid",
    benefits: "Depuffs, brightens dark circles, smooths fine lines.",
    directions: "Gently tap a small amount around the eye area.",
    skinType: "All skin types",
    weight: "15 ml",
    sku: "FG-SKI-016"
  },
  {
    name: "Exfoliating Body Scrub",
    category: "Body Care",
    price: 2822,
    mrp: 3320,
    discount: 15,
    images: ["https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?q=80&w=800&auto=format&fit=crop"],
    rating: 4.7,
    numReviews: 105,
    description: "A sugar-based body scrub that polishes away dead skin cells for a smooth, glowing finish.",
    ingredients: "Brown Sugar, Coconut Oil, Vanilla Extract",
    benefits: "Exfoliates, softens, improves texture.",
    directions: "Massage onto damp skin in circular motions, then rinse.",
    skinType: "Normal, Dry",
    weight: "200 g",
    sku: "FG-BOD-017"
  },
  {
    name: "Balancing Toner",
    category: "Skincare",
    price: 2158,
    mrp: 2158,
    discount: 0,
    images: ["https://images.unsplash.com/photo-1556228578-0d85b1a4d571?q=80&w=800&auto=format&fit=crop"],
    rating: 4.5,
    numReviews: 190,
    description: "An alcohol-free toner that restores skin's pH balance and refines pores.",
    ingredients: "Witch Hazel, Rose Water, Aloe Vera",
    benefits: "Balances pH, minimizes pores, refreshes.",
    directions: "Apply with a cotton pad after cleansing.",
    skinType: "All skin types",
    weight: "150 ml",
    sku: "FG-SKI-018"
  },
  {
    name: "Overnight Lip Mask",
    category: "Lip Care",
    price: 1660,
    mrp: 2075,
    discount: 20,
    images: ["https://images.unsplash.com/photo-1586495777744-4413f21062fa?q=80&w=800&auto=format&fit=crop"],
    rating: 4.9,
    numReviews: 340,
    description: "A leave-on lip mask that deeply hydrates and repairs lips while you sleep.",
    ingredients: "Berry Mix Complex, Vitamin C, Hyaluronic Acid",
    benefits: "Intense hydration, softens lips, repairs chapping.",
    directions: "Apply a generous layer to lips before bed.",
    skinType: "All skin types",
    weight: "20 g",
    sku: "FG-LIP-019"
  },
  {
    name: "Daily Defense Shampoo",
    category: "Hair Care",
    price: 1826,
    mrp: 1826,
    discount: 0,
    images: ["https://images.unsplash.com/photo-1522337660859-02fbefca4702?q=80&w=800&auto=format&fit=crop"],
    rating: 4.4,
    numReviews: 155,
    description: "A gentle, sulfate-free shampoo that cleanses and protects hair from daily environmental stress.",
    ingredients: "Aloe Vera, Panthenol, Green Tea Extract",
    benefits: "Cleanses, protects color, adds shine.",
    directions: "Massage into wet hair and scalp, then rinse thoroughly.",
    skinType: "N/A",
    weight: "250 ml",
    sku: "FG-HAI-020"
  }
];

const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const seedDB = async () => {
  try {
    console.log('Connecting to PostgreSQL database...');

    await prisma.order.deleteMany();
    await prisma.product.deleteMany();
    await prisma.user.deleteMany();

    const createdProducts = await prisma.product.createMany({
      data: products
    });
    console.log(`${createdProducts.count} Products Imported!`);

    process.exit();
  } catch (error) {
    console.error(`Error: ${error.message}`);
    process.exit(1);
  }
};

seedDB();
